  Exercise 1:

Create a 5x5 matrix with random integers from a normal distribution with mean 0 and standard deviation 1.

  Exercise 2:

Given a 2D array, calculate the sum of all columns, and then find the column with the maximum sum.

  Exercise 3:

Create a random 100x100 matrix and compute the mean of each row without using any loops.

  Exercise 4:

Create a 3x3 matrix with random integers and normalize each row to have a sum of 1.

  Exercise 5:

Given a 1D array, remove all elements between the 25th and 75th percentiles.

  Exercise 6:

Create a 4x4 matrix with a checkerboard pattern of 0s and 1s (Hint: use np.tile).

  Exercise 7:

Implement the matrix multiplication of two 3x3 matrices without using the np.dot or @ operator.

  Exercise 8:

Given a 2D array, calculate the Euclidean distance between each pair of rows.

  Exercise 9:

Create a 5x5 matrix with values ranging from 1 to 25, and then replace all even elements with the square root of their values.

  Exercise 10:

Implement a function to find the local maxima (peaks) in a 1D array. A local maximum is an element greater than its neighbors.

  Exercise 11:

Generate a 3D array with dimensions (5, 5, 5) and compute the sum along the third axis.

  Exercise 12:

Given a 2D array, replace all negative values with the absolute values.

  Exercise 13:

Implement a function to calculate the moving average over a given window size for a 1D array.

  Exercise 14:

Create a 6x6 matrix with a pattern such that each element is the sum of its indices (i, j) and its neighbors (i-1, j-1), (i-1, j), (i, j-1).

  Exercise 15:

Given a 2D array, find the most frequent value in each column.

  Exercise 16:

Create a 10x10 matrix with random integers and replace all values greater than 5 and less than 10 with the median value.

  Exercise 17:

Implement a function to compute the cross-correlation of two 1D arrays.

  Exercise 18:

Create a 2D array with values from a Poisson distribution with a given lambda parameter.

  Exercise 19:

Given two arrays, find the set exclusive-or of their elements (symmetric difference).

  Exercise 20:

Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal.

  Exercise 21:

Given a 2D array, find the indices of the maximum and minimum values along each row.

  Exercise 22:

Create a random 10x10 matrix and compute the matrix rank.

25 Exercises for NumPy Python library

In [529]:
import numpy as np

In [84]:
"""
Exercise 1:
Create a 5x5 matrix with random integers from a normal distribution with mean 0 and standard
deviation 1.
"""

# Random 5x5 matrix
arr = np.random.normal(loc=0, scale=1.0, size=(5,5))  
# loc = mean of the distribution, scale = standard deviation

print(arr)

[[-2.46572787 -0.1583444  -0.23228772 -1.52876404  0.19184019]
 [-1.20727756  1.01382878 -0.55244665  0.29352984  0.23455846]
 [ 1.17650631 -0.00675845 -1.15742021  0.35231281  0.29633542]
 [ 0.22791841  0.12206842 -1.15203954 -0.73711556 -0.76789093]
 [ 0.53040704 -0.76060878 -0.16554232 -0.46405683  0.96943686]]


In [161]:
"""
Exercise 2:
Given a 2D array, calculate the sum of all columns, and then find the column with the maximum sum.
"""

# Random 5x5 matrix with random int values from [0, 9] 
arr = np.random.randint(10, size=(5, 5)) 
sum_columns = np.sum(arr, axis=0)  # axis=0 means columns, axis=1 means rows

print(f"Index of the column with sum max: {np.argmax(sum_columns)}")

Index of the column with sum max: 3


In [175]:
"""
Exercise 3:
Create a random 100x100 matrix and compute the mean of each row without using any loops.
"""

# Random 100x100 matrix with int values from [0, 4]
arr = np.random.randint(5, size=(100, 100))  
mean_rows = np.mean(arr, axis=1)  # mean values for every row

print(mean_rows)

[1.96 1.89 2.   2.2  1.88 1.76 1.9  2.29 2.02 1.91 1.98 2.01 2.04 2.
 1.86 2.18 1.92 1.94 2.36 2.23 1.63 2.16 1.77 2.22 2.13 2.21 1.92 1.88
 1.96 2.12 1.91 2.   1.97 1.94 1.76 1.99 1.91 1.74 1.74 1.94 2.03 2.23
 1.88 2.24 2.12 2.13 2.04 2.02 2.16 1.99 2.14 2.27 2.02 1.93 1.82 2.
 2.05 1.85 1.85 2.05 1.81 1.91 1.92 1.8  1.62 2.03 1.88 2.15 2.3  2.1
 1.85 2.09 2.17 2.02 2.15 1.95 1.77 1.92 2.   1.99 2.1  2.15 2.02 2.01
 2.13 2.07 1.89 2.07 2.12 2.09 2.03 1.78 1.98 2.09 2.15 2.03 2.03 1.84
 1.82 2.28]


In [457]:
"""
Exercise 4:
Create a 3x3 matrix with random integers and normalize each row to have a sum of 1.
"""

# Random 3x3 matrix with int values from [0, 9]
arr = np.random.randint(10, size=(3, 3))  

#  Divide each element (in the row) by the sum of all elements in that row, resulting in a sum = 1
norm_arr = arr / arr.sum(axis=1, keepdims=True)

print(norm_arr)

[[2 7 3]
 [3 1 2]
 [2 7 2]]
[[0.16666667 0.58333333 0.25      ]
 [0.5        0.16666667 0.33333333]
 [0.18181818 0.63636364 0.18181818]]


In [441]:
"""
Exercise 5:
Given a 1D array, remove all elements between the 25th and 75th percentiles.
"""

# Random 1D array with size = 36, int values between [1, 9]
arr = np.random.randint(10, size=(36))

# Start index and end index
start = int(0.25 * len(arr))
end = int(0.75 * len(arr))

# Boolean mask to keep the elements outside the specified range
to_keep = (np.arange(len(arr)) < start) | (np.arange(len(arr)) > end)

# New array with the selected elements
new_arr = arr[to_keep]

print(new_arr)

[4 9 0 2 3 7 1 8 2 5 3 4 8 6 2 1 0]


In [280]:
"""
Exercise 6:
Create a 4x4 matrix with a checkerboard pattern of 0s and 1s (with np.tile).
"""

# Array with 0s and 1s alternating, using np.tile to repeat the pattern.
arr = np.tile([[0, 1], [1, 0]], (2, 2))

print(arr)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [300]:
"""
Exercise 7:
Implement the matrix multiplication of two 3x3 matrices without using the np.dot or @ operator.
"""

# Matrix 1 with values from [1, 9], matrix 2 with values from [11, 19]
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(11, 20).reshape(3, 3)

# Initialize an array for the result
main_arr = np.zeros((3, 3), dtype=int)

for i in range(3):  # Iterate over rows
    for j in range(3):  # Iterate over columns
        for k in range(3): # Iterate over columns in matrix 1 and rows in matrix 2
            main_arr[i, j] += arr1[i, k] * arr2[k, j]

print(main_arr)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [386]:
"""
Exercise 8:
Given a 2D array, calculate the Euclidean distance between each pair of rows.
"""

# Random 4x4 matrix with int values between [1, 10]
arr = np.random.randint(1, 11, size=(4,4))

# Using a for loop to iterate through row pairs, using numpy.linalg.norm to calculate Eucl. dist.
for row in range(3):
    eucl_distance = np.linalg.norm(arr[row + 1] - arr[row])
    print(f"The Euclidean distance between row {row + 2} and row {row + 1} is {eucl_distance}.")

The Euclidean distance between row 2 and row 1 is 7.615773105863909.
The Euclidean distance between row 3 and row 2 is 5.0990195135927845.
The Euclidean distance between row 4 and row 3 is 6.082762530298219.


In [400]:
"""
Exercise 9:
Create a 5x5 matrix with values ranging from 1 to 25, and then replace all even elements 
with the square root of their values.
"""

# 5x5 matrix with int values from [1, 25]
arr = np.arange(1, 26).reshape(5, 5)

# New matrix with even values equal to their square root.
new_arr = np.where(arr % 2 == 0, np.sqrt(arr), arr)

print(new_arr)

[[ 1.          1.41421356  3.          2.          5.        ]
 [ 2.44948974  7.          2.82842712  9.          3.16227766]
 [11.          3.46410162 13.          3.74165739 15.        ]
 [ 4.         17.          4.24264069 19.          4.47213595]
 [21.          4.69041576 23.          4.89897949 25.        ]]


In [532]:
"""
Exercise 10:
Implement a function to find the local maxima (peaks) in a 1D array. 
A local maximum is an element greater than its neighbors.
"""

# Random array with values from [1, 10] and size = 20
arr = np.random.randint(1, 11, 20)

# Extract the indices of peaks
peaks_indices = np.where((arr[1:-1] > arr[:-2]) & (arr[1:-1] > arr[2:]))[0] + 1

# Extract the values coresponding to their indices
peaks_values = arr[peaks_indices]

print(peaks_values)

[ 9  6  5 10  9]


In [556]:
"""
Exercise 11:
Generate a 3D array with dimensions (5, 5, 5) and compute the sum along the third axis.
"""

# Random 5x5x5 matrix with int values between [1, 10]
arr = np.random.randint(1, 11, size=(5, 5, 5))

# The sum along the third axis
z_sums = np.sum(arr, axis=2)  # axis=2 means z axis

print(z_sums)

[[34 17 27 25 39]
 [29 26 30 31 20]
 [23 41 43 19 30]
 [28 32 28 38 35]
 [27 23 28 35 23]]


In [597]:
"""
Exercise 12:
Given a 2D array, replace all negative values with the absolute values.
"""

# Random 4x4 matrix with int values from [-10, 10]
arr = np.random.randint(-10, 11, size=(4, 4))

# New matrix that replaces all negative values with their absolute values
new_arr = np.where(arr < 0, -arr, arr)

print(new_arr)

[[ 1  6  7  6]
 [ 2 10  5 10]
 [ 2  1  8  1]
 [ 4  9 10  2]]


In [647]:
"""
Exercise 13:
Implement a function to calculate the moving average over a given window size for a 1D array.
"""

# Random array with values between [1, 10] and size = 20
arr = np.random.randint(1, 11, size=20)

# Calculates the cumulative sum of the entire array
cumulative_sum = np.cumsum(arr)

# Example of window size
size = 5

# Calculates the sum of elements withing the window
cumulative_sum[size:] = cumulative_sum[size:] - cumulative_sum[:-size]

# Calculates the moving average by taking the sum and dividing it by the size of the window
result = cumulative_sum[size - 1:] / size

print(result)

[5.8 4.6 4.4 4.4 4.4 3.8 4.2 5.4 4.2 4.4 4.4 5.  3.8 4.4 5.8 5. ]


In [79]:
"""
Exercise 14:
Create a 6x6 matrix with a pattern such that each element is the sum of its indices (i, j) and 
its neighbors (i-1, j-1),(i-1, j), (i, j-1).
"""

# Create a matrix 
arr = np.zeros((6, 6), dtype=int)

# Loop through every element and calculate the sum for each one
for i in range(0, 6):
    for j in range(0, 6):
        arr[i, j] = i + j + arr[i-1, j-1] + arr[i-1, j] + arr[i, j-1]

print(arr)

[[     0      1      3      6     10     15]
 [    16     19     26     39     60     91]
 [   109    147    196    266    371    529]
 [   641    901   1249   1717   2361   3269]
 [  3914   5461   7617  10590  14676  20315]
 [ 24234  33615  46700  64915  90190 125191]]


In [154]:
"""
Exercise 15:
Given a 2D array, find the most frequent value in each column.
"""

# Create a random 10x10 matrix in integers from [1, 10]
arr = np.random.randint(1, 11, size=(10, 10))

# Construct an array that receives the most frequent value for each column
most_frequent = np.apply_along_axis(lambda x: np.bincount(x).argmax(), axis=0, arr=arr)

print(arr)
print(most_frequent)

[[ 1  1  9  3  3  6  2  3  7  4]
 [ 9  4  7  4  7  4  4  8  8  6]
 [ 7  2  5  1  9  2 10  7  6  8]
 [ 3  8  8  5  6  4  8  5  4  2]
 [ 6  1  8  5  1  7  6  9  1  4]
 [ 9  3  8  2  3  9  7  9  1  3]
 [10  9  1  7 10  1  5  7  3  9]
 [ 6  9  9  9  8  2 10 10 10  3]
 [ 2 10  7  3  4  7 10  2  6  7]
 [10  3  5 10  7 10  2  9  3  9]]
[ 6  1  8  3  3  2 10  9  1  3]


In [212]:
"""
Exercise 16:
Create a 10x10 matrix with random integers and replace all values greater than 5 and less than 10 with the median value.
"""

# Create a random 10x10 matrix with int values from [1, 10]
arr = np.random.randint(1, 11, size=(10, 10))

# Create a new array that replaces every value from [6, 9] with the median value
new_arr = np.where((5 < arr) & (arr < 10) , np.median(arr), arr)

print(new_arr)

[[ 6. 10.  4.  3.  6.  5.  6.  3.  6.  6.]
 [ 6.  5.  1.  3.  6.  6.  6.  6.  2.  1.]
 [ 4.  6.  6.  6.  6.  3.  6.  6.  1.  1.]
 [ 6.  3.  4.  6. 10.  3.  3.  6.  6.  6.]
 [ 5.  5. 10.  6.  6.  5.  2.  6.  6.  1.]
 [ 5.  6.  4.  6.  6.  1.  5.  4.  5.  3.]
 [ 6.  2. 10.  6.  6.  2.  6. 10.  6.  3.]
 [ 2.  6.  3.  6.  1.  3.  4.  6. 10.  3.]
 [ 6.  1.  6.  6. 10.  4.  6.  2.  6.  1.]
 [ 6.  6.  3.  6. 10.  6.  6.  1.  6.  6.]]


In [238]:
"""
Exercise 17:
Implement a function to compute the cross-correlation of two 1D arrays.
"""

# Create 2 random arrays with length 20 and int values from [1, 10]
arr1 = np.random.randint(1, 11, 20)
arr2 = np.random.randint(1, 11, 20)

# Create the correlation result between the two arrays
correlation = np.correlate(arr1, arr2)

print(arr1)
print(arr2)
print(correlation)

[5 7 4 3 3 1 3 3 7 3 8 1 8 1 5 8 3 8 3 2]
[ 3  2  9  3  4  3  2  6  3  6 10  2  1  7  4  2  6  7  5  9]
[392]


In [294]:
"""
Exercise 18:
Create a 2D array with values from a Poisson distribution with a given lambda parameter.
"""

# Set the value for lambda
lambda_val = 4

# Create a maxtrix with values from a Poisson distribution
arr = np.random.poisson(lambda_val, size=(8, 8))

print(arr)

[[3 1 8 6 4 3 3 5]
 [3 4 2 6 1 1 0 2]
 [7 4 7 2 4 5 2 6]
 [2 3 1 2 6 1 2 6]
 [5 3 3 0 5 4 4 3]
 [5 3 6 5 6 4 8 3]
 [1 5 4 3 7 6 5 7]
 [3 2 4 2 5 3 4 0]]


In [390]:
"""
Exercise 19:
Given two arrays, find the set exclusive-or of their elements (symmetric difference).
"""

# Create 2 random arrays with length 5 and int values from [1, 7]
arr1 = np.random.randint(1, 8, 5)
arr2 = np.random.randint(1, 8, 5)

print(arr1)
print(arr2)

# Create a symmetric difference array
symmetric_difference = np.setxor1d(arr1, arr2)

print(symmetric_difference)

[6 4 6 5 5]
[7 5 7 1 7]
[1 4 6 7]


In [395]:
"""
Exercise 20:
Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal.
"""

# Create a matrix with values 1, 2, 3 and 4 below the diagonal
matrix = np.diag([1, 2, 3, 4], k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [473]:
"""
Exercise 21:
Given a 2D array, find the indices of the maximum and minimum values along each row.
"""

# Create a random 7x7 matrix with int values from [1, 10]
matrix = np.random.randint(1, 11, size=(7, 7))

# Construct 2 arrays for the min and max indices values along each row
max_indices = np.argmax(matrix, axis=1)
min_indices = np.argmin(matrix, axis=1)

print(matrix)
print(max_indices)
print(min_indices)

[[ 6  8  9 10  5  7  2]
 [10  2  9  5  9  8  2]
 [ 9  5 10  7  6  1  8]
 [ 1  8 10  4 10  7  8]
 [ 7  7  2  1  4  5  5]
 [ 4  9  9  2  3  2  8]
 [ 5  9  8  3  6  9  2]]
[3 0 2 2 0 1 1]
[6 1 5 0 3 3 6]


In [523]:
"""
Exercise 22:
Create a random 10x10 matrix and compute the matrix rank.
"""
# Create a random 10x10 matrix with int values from [1, 10]
matrix = np.random.randint(1, 11, size=(10, 10))

# Find the rank using linalg.matrix_rank function
rank = np.linalg.matrix_rank(matrix)

print(f"The matrix rank is {rank}")

The matrix rank is 10
